export const GET_ALL_COURSE_BY_TEACHER = "GET_ALL_COURSE_BY_TEACHER"
export const GET_ALL_COURSE_BY_TEACHER_SEMESTER = "GET_ALL_COURSE_BY_TEACHER_SEMESTER"
export const GET_ALL_COURSE_BY_COURSE = "GET_ALL_COURSE_BY_COURSE"